/*****************************************************************************
* Model: query.qm
* File:  ./QueryEngine.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${System::.::QueryEngine.h} ..............................................*/
#pragma once

#include "Engine.h"
#include "Query.h"

QActive *AO_QueryEngine(void);

/*${System::QueryEngine} ...................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QEvt const * evtStorage[128];
    QTimeEvt stepTout;
    QTimeEvt queryTout;
    Request_p request;
    QTimeEvt stepACKTout;
} QueryEngine;

/* public: */
void QueryEngine_ctor(QueryEngine * const me);

/* protected: */
QState QueryEngine_initial(QueryEngine * const me, QEvt const * const e);
QState QueryEngine_Idle(QueryEngine * const me, QEvt const * const e);
QState QueryEngine_Working(QueryEngine * const me, QEvt const * const e);
QState QueryEngine_StepInit(QueryEngine * const me, QEvt const * const e);
QState QueryEngine_StepWaiting(QueryEngine * const me, QEvt const * const e);
QState QueryEngine_StepFailed(QueryEngine * const me, QEvt const * const e);

